import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Feed from './components/Feed'
import LeftSidebar from './components/LeftSidebar'
import RightSidebar from './components/RightSidebar'

const Home: NextPage = () => {
  return (
    <div className="mx-auto mt-3 max-h-screen overflow-hidden lg:max-w-6xl">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-9">
        <LeftSidebar />

        <Feed />

        <RightSidebar />
      </main>
    </div>
  )
}

export default Home
